### ISSUE TITLE
Migrate Let's Encrypt Certbot configuration to PfSense

### ISSUE THREAD

**Issue by clee231** [acm-uic/IaC#13]
ACME Certificates is a plugin that allows pfSense to handle the Let's Encrypt renewals.

This needs to be done on all the certs used on chopin.

## Acceptance Criteria

- [x] Inventory of all certificates have been noted
- [x] Current certificates have been uploaded to the Certificate manager
- [x] Certbot is disabled on chopin

## Additional Information
* https://certbot.eff.org/
