### ISSUE TITLE
Create GitHub secrets for interacting with Proxmox & Azure

### ISSUE THREAD

**Issue by clee231** [acm-uic/IaC#9]
We want to define as much of our infrastructure in code as possible. In order for automated pipeline to work, we need to give this pipelines under this repo (`IaC`) the ability to credentials to interact with our infrastructure. One of the first steps is to give our tools the access it needs to make infrastructure changes.

**Acceptance Criteria**
- [ ] Create a new Terraform stack to create the service account in Azure
- [ ] Create environment secrets for Terraform to interact with Proxmox
- [ ] Create environment secrets for Terraform to interact with Azure
